# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Zhu23ABS_tafc_cpp <- function(start_point, trial_stim, distr_name, mc3_iterations, n_chains, dec_bdry, discrim, prior_on_resp, delta, nd_time, s_nd_time, er_lambda, proposal_width) {
    .Call(`_samplr_Zhu23ABS_tafc_cpp`, start_point, trial_stim, distr_name, mc3_iterations, n_chains, dec_bdry, discrim, prior_on_resp, delta, nd_time, s_nd_time, er_lambda, proposal_width)
}

Zhu23ABS_pj_cpp <- function(start_point, trial_stim, distr_name, n_chains, trial_bdry, prior_on_resp, delta, nd_time, s_nd_time, er_lambda, proposal_width) {
    .Call(`_samplr_Zhu23ABS_pj_cpp`, start_point, trial_stim, distr_name, n_chains, trial_bdry, prior_on_resp, delta, nd_time, s_nd_time, er_lambda, proposal_width)
}

sampler_hmc_cpp <- function(start, distr_name, distr_params, epsilon, L, iterations, isMix, weights, custom_func, useCustom) {
    .Call(`_samplr_sampler_hmc_cpp`, start, distr_name, distr_params, epsilon, L, iterations, isMix, weights, custom_func, useCustom)
}

sampler_mc3_cpp <- function(start, nChains, sigma_prop, delta_T, swap_all, iterations, distr_name, distr_params, discreteValues, isMix, weights, custom_func, useCustom, alpha = 0) {
    .Call(`_samplr_sampler_mc3_cpp`, start, nChains, sigma_prop, delta_T, swap_all, iterations, distr_name, distr_params, discreteValues, isMix, weights, custom_func, useCustom, alpha)
}

sampler_mc_rec_cpp <- function(start, nChains, delta_T, swap_all, iterations, distr_name, distr_params, discreteValues, isMix, weights, custom_func, useCustom, epsilon, L, alpha) {
    .Call(`_samplr_sampler_mc_rec_cpp`, start, nChains, delta_T, swap_all, iterations, distr_name, distr_params, discreteValues, isMix, weights, custom_func, useCustom, epsilon, L, alpha)
}

sampler_mh_cpp <- function(start, sigma_prop, iterations, distr_name, distr_params, discreteValues, isMix, weights, custom_func, useCustom, alpha = 0) {
    .Call(`_samplr_sampler_mh_cpp`, start, sigma_prop, iterations, distr_name, distr_params, discreteValues, isMix, weights, custom_func, useCustom, alpha)
}

sampler_nuts_cpp <- function(start, distr_name, distr_params, epsilon, iterations, delta_max, isMix, weights, custom_func, useCustom) {
    .Call(`_samplr_sampler_nuts_cpp`, start, distr_name, distr_params, epsilon, iterations, delta_max, isMix, weights, custom_func, useCustom)
}

gridDensity_cpp <- function(distr_name, distr_params, isMix, weights, xxRange, yyRange, cellsPerRow, densityFunc, useCustomDensity) {
    .Call(`_samplr_gridDensity_cpp`, distr_name, distr_params, isMix, weights, xxRange, yyRange, cellsPerRow, densityFunc, useCustomDensity)
}

