# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

subset_range <- function(x, start, end) {
    .Call(`_samplr_subset_range`, x, start, end)
}

support <- function(chain, dec_bdry, start_bias) {
    .Call(`_samplr_support`, chain, dec_bdry, start_bias)
}

cumsum_sug <- function(x) {
    .Call(`_samplr_cumsum_sug`, x)
}

concatenate_vectors <- function(a, b) {
    .Call(`_samplr_concatenate_vectors`, a, b)
}

checkThreshold <- function(cumSupp, delta, caution) {
    .Call(`_samplr_checkThreshold`, cumSupp, delta, caution)
}

new_start_point <- function(chain, nChains, position, iterations) {
    .Call(`_samplr_new_start_point`, chain, nChains, position, iterations)
}

give_me_sign <- function(x) {
    .Call(`_samplr_give_me_sign`, x)
}

ABS_sampler_cpp <- function(start_point, trial_fdbk, distr_name, nChains, dec_bdry, d_sepn, delta, nd_time, s_nd_time, er_lambda, mc3_iterations, proposal_width) {
    .Call(`_samplr_ABS_sampler_cpp`, start_point, trial_fdbk, distr_name, nChains, dec_bdry, d_sepn, delta, nd_time, s_nd_time, er_lambda, mc3_iterations, proposal_width)
}

sampler_hmc_cpp <- function(start, distr_name, distr_params, epsilon, L, iterations, isMix, weights, custom_func, useCustom) {
    .Call(`_samplr_sampler_hmc_cpp`, start, distr_name, distr_params, epsilon, L, iterations, isMix, weights, custom_func, useCustom)
}

sampler_mc3_cpp <- function(start, nChains, sigma_prop, delta_T, swap_all, iterations, distr_name, distr_params, discreteValues, isMix, weights, custom_func, useCustom, alpha = 0) {
    .Call(`_samplr_sampler_mc3_cpp`, start, nChains, sigma_prop, delta_T, swap_all, iterations, distr_name, distr_params, discreteValues, isMix, weights, custom_func, useCustom, alpha)
}

sampler_mc_rec_cpp <- function(start, nChains, delta_T, swap_all, iterations, distr_name, distr_params, discreteValues, isMix, weights, custom_func, useCustom, epsilon, L, alpha) {
    .Call(`_samplr_sampler_mc_rec_cpp`, start, nChains, delta_T, swap_all, iterations, distr_name, distr_params, discreteValues, isMix, weights, custom_func, useCustom, epsilon, L, alpha)
}

sampler_mh_cpp <- function(start, sigma_prop, iterations, distr_name, distr_params, discreteValues, isMix, weights, custom_func, useCustom, alpha = 0) {
    .Call(`_samplr_sampler_mh_cpp`, start, sigma_prop, iterations, distr_name, distr_params, discreteValues, isMix, weights, custom_func, useCustom, alpha)
}

sampler_nuts_cpp <- function(start, distr_name, distr_params, epsilon, iterations, delta_max, isMix, weights, custom_func, useCustom) {
    .Call(`_samplr_sampler_nuts_cpp`, start, distr_name, distr_params, epsilon, iterations, delta_max, isMix, weights, custom_func, useCustom)
}

gridDensity_cpp <- function(distr_name, distr_params, isMix, weights, xxRange, yyRange, cellsPerRow, densityFunc, useCustomDensity) {
    .Call(`_samplr_gridDensity_cpp`, distr_name, distr_params, isMix, weights, xxRange, yyRange, cellsPerRow, densityFunc, useCustomDensity)
}

